-- ============================================================
-- Manual DDL patch — Safety_MultiFile migration (empty Up())
-- Run this directly in PostgreSQL (psql or pgAdmin etc.)
-- ============================================================

-- 1. Add ReportDate column (if not already present)
ALTER TABLE "SafetyWkReps" ADD COLUMN IF NOT EXISTS "ReportDate" date;

-- 2. Drop old single-file columns
ALTER TABLE "SafetyWkReps" DROP COLUMN IF EXISTS "FileName";
ALTER TABLE "SafetyWkReps" DROP COLUMN IF EXISTS "StoredFileName";
ALTER TABLE "SafetyWkReps" DROP COLUMN IF EXISTS "Extension";
ALTER TABLE "SafetyWkReps" DROP COLUMN IF EXISTS "FileSize";

-- 3. Create SafetyWkRepFiles table
CREATE TABLE IF NOT EXISTS "SafetyWkRepFiles" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReportId"       integer NOT NULL
                         REFERENCES "SafetyWkReps"("Id") ON DELETE CASCADE,
    "FileName"       character varying(260) NOT NULL DEFAULT '',
    "StoredFileName" character varying(100) NOT NULL DEFAULT '',
    "Extension"      character varying(20),
    "FileSize"       bigint NOT NULL DEFAULT 0,
    "UploadedById"   integer REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UploadedByName" character varying(150),
    "UploadedAt"     timestamp with time zone,
    "IsActive"       boolean NOT NULL DEFAULT true,
    "CreatedAt"      timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt"      timestamp with time zone NOT NULL DEFAULT now(),
    "CreatedById"    integer,
    "UpdatedById"    integer
);

-- 4. Indexes on SafetyWkRepFiles
CREATE INDEX IF NOT EXISTS "IX_SafetyWkRepFiles_ReportId"
    ON "SafetyWkRepFiles"("ReportId");

CREATE INDEX IF NOT EXISTS "IX_SafetyWkRepFiles_UploadedById"
    ON "SafetyWkRepFiles"("UploadedById");
