using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ACI.Web.Migrations
{
    /// <inheritdoc />
    public partial class AddPrivilegeEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── 모든 구문을 idempotent 하게 처리 ──────────────────────────────────
            // 이 마이그레이션은 DB 에 이미 일부 테이블/컬럼이 존재하는 환경에서도
            // 안전하게 재실행될 수 있도록 IF NOT EXISTS / EXCEPTION 가드를 사용합니다.

            // ── 1. Users.Role 제거 (IF EXISTS: 첫 실행 실패 후 롤백 시 아직 존재할 수 있음) ──
            migrationBuilder.Sql(@"ALTER TABLE ""Users"" DROP COLUMN IF EXISTS ""Role"";");

            // ── 2. ScheduleRevisions.BaselineId 추가 (이미 존재할 수 있음) ────────
            migrationBuilder.Sql(@"ALTER TABLE ""ScheduleRevisions"" ADD COLUMN IF NOT EXISTS ""BaselineId"" integer;");

            // ── 3. Privileges 테이블 ──────────────────────────────────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Privileges"" (
                    ""Id""          integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Code""        character varying(50)  NOT NULL,
                    ""Name""        character varying(100) NOT NULL,
                    ""Description"" character varying(500),
                    ""IsBuiltIn""   boolean NOT NULL,
                    ""IsActive""    boolean NOT NULL,
                    ""CreatedAt""   timestamp with time zone NOT NULL,
                    ""UpdatedAt""   timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Privileges"" PRIMARY KEY (""Id"")
                );
            ");

            // ── 4. ScheduleBaselines 테이블 (이미 존재할 수 있음) ─────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ScheduleBaselines"" (
                    ""Id""                 integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProjectId""          integer NOT NULL,
                    ""VersionNumber""      integer NOT NULL,
                    ""Title""             character varying(200) NOT NULL,
                    ""Description""       character varying(2000),
                    ""Status""            integer NOT NULL,
                    ""FrozenAt""          timestamp with time zone,
                    ""FrozenById""        integer,
                    ""FrozenByName""      character varying(150),
                    ""SubmittedAt""       timestamp with time zone,
                    ""ApprovedAt""        timestamp with time zone,
                    ""ApprovedByName""    character varying(150),
                    ""ApprovalNotes""     character varying(1000),
                    ""DataDate""          date,
                    ""IsAutoSnapshot""    boolean NOT NULL,
                    ""SourceSimulationId"" integer,
                    ""TaskCount""         integer NOT NULL,
                    ""EarliestStart""     date,
                    ""LatestFinish""      date,
                    ""TotalCalendarDays"" integer,
                    ""IsActive""          boolean NOT NULL,
                    ""CreatedAt""         timestamp with time zone NOT NULL,
                    ""UpdatedAt""         timestamp with time zone NOT NULL,
                    ""CreatedById""       integer,
                    ""UpdatedById""       integer,
                    CONSTRAINT ""PK_ScheduleBaselines"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""ScheduleBaselines"" ADD CONSTRAINT ""FK_ScheduleBaselines_Projects_ProjectId""
                        FOREIGN KEY (""ProjectId"") REFERENCES ""Projects"" (""Id"") ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""ScheduleBaselines"" ADD CONSTRAINT ""FK_ScheduleBaselines_Users_FrozenById""
                        FOREIGN KEY (""FrozenById"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");

            // ── 5. UserPrivileges 테이블 (신규) ───────────────────────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""UserPrivileges"" (
                    ""UserId""          integer NOT NULL,
                    ""PrivilegeId""     integer NOT NULL,
                    ""GrantedAt""       timestamp with time zone NOT NULL,
                    ""GrantedByUserId"" integer,
                    CONSTRAINT ""PK_UserPrivileges"" PRIMARY KEY (""UserId"", ""PrivilegeId"")
                );
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""UserPrivileges"" ADD CONSTRAINT ""FK_UserPrivileges_Privileges_PrivilegeId""
                        FOREIGN KEY (""PrivilegeId"") REFERENCES ""Privileges"" (""Id"") ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""UserPrivileges"" ADD CONSTRAINT ""FK_UserPrivileges_Users_GrantedByUserId""
                        FOREIGN KEY (""GrantedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""UserPrivileges"" ADD CONSTRAINT ""FK_UserPrivileges_Users_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");

            // ── 6. BaselineTaskSnapshots 테이블 (이미 존재할 수 있음) ─────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BaselineTaskSnapshots"" (
                    ""Id""                   integer GENERATED BY DEFAULT AS IDENTITY,
                    ""BaselineId""           integer NOT NULL,
                    ""SourceScheduleTaskId"" integer,
                    ""SourceWorkingTaskId""  integer,
                    ""WbsCode""              character varying(30),
                    ""Text""                 character varying(300) NOT NULL,
                    ""Description""          character varying(1000),
                    ""Location""             character varying(200),
                    ""TaskType""             integer NOT NULL,
                    ""ParentSnapshotId""     integer,
                    ""SortOrder""            integer NOT NULL,
                    ""IsOpen""               boolean NOT NULL,
                    ""TradeId""              integer,
                    ""TradeName""            character varying(100),
                    ""TradeColor""           character varying(10),
                    ""AssignedToId""         integer,
                    ""AssignedToName""       character varying(150),
                    ""StartDate""            date NOT NULL,
                    ""EndDate""              date NOT NULL,
                    ""Duration""             integer NOT NULL,
                    ""Progress""             double precision NOT NULL,
                    ""ActualStartDate""      date,
                    ""ActualEndDate""        date,
                    ""ConstraintType""       integer,
                    ""ConstraintDate""       date,
                    ""Color""                character varying(10),
                    ""CrewSize""             integer NOT NULL,
                    ""Notes""                character varying(1000),
                    CONSTRAINT ""PK_BaselineTaskSnapshots"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""BaselineTaskSnapshots""
                        ADD CONSTRAINT ""FK_BaselineTaskSnapshots_BaselineTaskSnapshots_ParentSnapshotId""
                        FOREIGN KEY (""ParentSnapshotId"") REFERENCES ""BaselineTaskSnapshots"" (""Id"") ON DELETE RESTRICT;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""BaselineTaskSnapshots""
                        ADD CONSTRAINT ""FK_BaselineTaskSnapshots_ScheduleBaselines_BaselineId""
                        FOREIGN KEY (""BaselineId"") REFERENCES ""ScheduleBaselines"" (""Id"") ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""BaselineTaskSnapshots""
                        ADD CONSTRAINT ""FK_BaselineTaskSnapshots_ScheduleTasks_SourceScheduleTaskId""
                        FOREIGN KEY (""SourceScheduleTaskId"") REFERENCES ""ScheduleTasks"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""BaselineTaskSnapshots""
                        ADD CONSTRAINT ""FK_BaselineTaskSnapshots_WorkingTasks_SourceWorkingTaskId""
                        FOREIGN KEY (""SourceWorkingTaskId"") REFERENCES ""WorkingTasks"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");

            // ── 7. ScheduleSimulations 테이블 (이미 존재할 수 있음) ───────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ScheduleSimulations"" (
                    ""Id""                integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProjectId""         integer NOT NULL,
                    ""Name""              character varying(200) NOT NULL,
                    ""Description""       character varying(2000),
                    ""Status""            integer NOT NULL,
                    ""SourceType""        integer NOT NULL,
                    ""SourceBaselineId""  integer,
                    ""CreatedByUserId""   integer,
                    ""CreatedByName""     character varying(150),
                    ""ModifiedTaskCount"" integer NOT NULL,
                    ""TotalDaysImpact""   integer,
                    ""SimulatedEndDate""  date,
                    ""IsActive""          boolean NOT NULL,
                    ""CreatedAt""         timestamp with time zone NOT NULL,
                    ""UpdatedAt""         timestamp with time zone NOT NULL,
                    ""CreatedById""       integer,
                    ""UpdatedById""       integer,
                    CONSTRAINT ""PK_ScheduleSimulations"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""ScheduleSimulations"" ADD CONSTRAINT ""FK_ScheduleSimulations_Projects_ProjectId""
                        FOREIGN KEY (""ProjectId"") REFERENCES ""Projects"" (""Id"") ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""ScheduleSimulations"" ADD CONSTRAINT ""FK_ScheduleSimulations_ScheduleBaselines_SourceBaselineId""
                        FOREIGN KEY (""SourceBaselineId"") REFERENCES ""ScheduleBaselines"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""ScheduleSimulations"" ADD CONSTRAINT ""FK_ScheduleSimulations_Users_CreatedByUserId""
                        FOREIGN KEY (""CreatedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");

            // ── 8. SimulationTasks 테이블 (이미 존재할 수 있음) ──────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""SimulationTasks"" (
                    ""Id""                  integer GENERATED BY DEFAULT AS IDENTITY,
                    ""SimulationId""        integer NOT NULL,
                    ""SourceWorkingTaskId"" integer,
                    ""SourceSnapshotId""    integer,
                    ""Text""               character varying(300),
                    ""StartDate""           date,
                    ""EndDate""             date,
                    ""Duration""            integer,
                    ""Progress""            double precision,
                    ""TradeId""             integer,
                    ""AssignedToId""        integer,
                    ""CrewSize""            integer,
                    ""Notes""               character varying(1000),
                    ""DaysShifted""         integer,
                    ""ChangeReason""        character varying(500),
                    ""IsNewTask""           boolean NOT NULL,
                    ""IsRemoved""           boolean NOT NULL,
                    CONSTRAINT ""PK_SimulationTasks"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""SimulationTasks"" ADD CONSTRAINT ""FK_SimulationTasks_BaselineTaskSnapshots_SourceSnapshotId""
                        FOREIGN KEY (""SourceSnapshotId"") REFERENCES ""BaselineTaskSnapshots"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""SimulationTasks"" ADD CONSTRAINT ""FK_SimulationTasks_ScheduleSimulations_SimulationId""
                        FOREIGN KEY (""SimulationId"") REFERENCES ""ScheduleSimulations"" (""Id"") ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""SimulationTasks"" ADD CONSTRAINT ""FK_SimulationTasks_WorkingTasks_SourceWorkingTaskId""
                        FOREIGN KEY (""SourceWorkingTaskId"") REFERENCES ""WorkingTasks"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");

            // ── 9. 인덱스 (모두 IF NOT EXISTS) ───────────────────────────────────
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Name"" ON ""Users"" (""Name"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ScheduleRevisions_BaselineId"" ON ""ScheduleRevisions"" (""BaselineId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_BaselineTaskSnapshots_BaselineId"" ON ""BaselineTaskSnapshots"" (""BaselineId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_BaselineTaskSnapshots_ParentSnapshotId"" ON ""BaselineTaskSnapshots"" (""ParentSnapshotId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_BaselineTaskSnapshots_SourceScheduleTaskId"" ON ""BaselineTaskSnapshots"" (""SourceScheduleTaskId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_BaselineTaskSnapshots_SourceWorkingTaskId"" ON ""BaselineTaskSnapshots"" (""SourceWorkingTaskId"");");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Privileges_Code"" ON ""Privileges"" (""Code"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ScheduleBaselines_FrozenById"" ON ""ScheduleBaselines"" (""FrozenById"");");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ScheduleBaselines_ProjectId_VersionNumber"" ON ""ScheduleBaselines"" (""ProjectId"", ""VersionNumber"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ScheduleSimulations_CreatedByUserId"" ON ""ScheduleSimulations"" (""CreatedByUserId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ScheduleSimulations_ProjectId"" ON ""ScheduleSimulations"" (""ProjectId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ScheduleSimulations_SourceBaselineId"" ON ""ScheduleSimulations"" (""SourceBaselineId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_SimulationTasks_SimulationId"" ON ""SimulationTasks"" (""SimulationId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_SimulationTasks_SourceSnapshotId"" ON ""SimulationTasks"" (""SourceSnapshotId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_SimulationTasks_SourceWorkingTaskId"" ON ""SimulationTasks"" (""SourceWorkingTaskId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_UserPrivileges_GrantedByUserId"" ON ""UserPrivileges"" (""GrantedByUserId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_UserPrivileges_PrivilegeId"" ON ""UserPrivileges"" (""PrivilegeId"");");

            // ── 10. ScheduleRevisions → ScheduleBaselines FK ─────────────────────
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""ScheduleRevisions"" ADD CONSTRAINT ""FK_ScheduleRevisions_ScheduleBaselines_BaselineId""
                        FOREIGN KEY (""BaselineId"") REFERENCES ""ScheduleBaselines"" (""Id"") ON DELETE SET NULL;
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ScheduleRevisions_ScheduleBaselines_BaselineId",
                table: "ScheduleRevisions");

            migrationBuilder.DropTable(
                name: "SimulationTasks");

            migrationBuilder.DropTable(
                name: "UserPrivileges");

            migrationBuilder.DropTable(
                name: "BaselineTaskSnapshots");

            migrationBuilder.DropTable(
                name: "ScheduleSimulations");

            migrationBuilder.DropTable(
                name: "Privileges");

            migrationBuilder.DropTable(
                name: "ScheduleBaselines");

            migrationBuilder.DropIndex(
                name: "IX_Users_Name",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_ScheduleRevisions_BaselineId",
                table: "ScheduleRevisions");

            migrationBuilder.DropColumn(
                name: "BaselineId",
                table: "ScheduleRevisions");

            migrationBuilder.AddColumn<int>(
                name: "Role",
                table: "Users",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }
    }
}
